CREATE TABLE notice(
`idx` INT NOT NULL AUTO_INCREMENT,
`notice_tit` TEXT NOT NULL,
`notice_content` LONGTEXT,
`notice_date` DATE,
`read_cnt` BIGINT,
PRIMARY KEY(`idx`)
)ENGINE=INNODB;


CREATE TABLE news(
`idx` INT NOT NULL AUTO_INCREMENT,
`news_tit` TEXT NOT NULL,
`news_content` LONGTEXT,
`news_date` DATE,
`read_cnt` BIGINT,
PRIMARY KEY(`idx`)
)ENGINE=INNODB;

CREATE TABLE download(
`idx` INT NOT NULL AUTO_INCREMENT,
`device` VARCHAR(32),
`file_path` VARCHAR(64),
`version` VARCHAR(12),
`reg_date` DATE,
PRIMARY KEY(`idx`)
)ENGINE=INNODB;

CREATE TABLE faq(
`idx` INT NOT NULL AUTO_INCREMENT,
`faq_tit` TEXT NOT NULL,
`faq_content` LONGTEXT,
`faq_date` DATE,
`read_cnt` BIGINT,
PRIMARY KEY (`idx`)
)ENGINE=INNODB;

CREATE TABLE biz(
idx INT NOT NULL AUTO_INCREMENT,
u_name VARCHAR(12) NOT NULL,
u_email VARCHAR(100) NOT NULL,
biz_name VARCHAR(120) NOT NULL,
country_name VARCHAR(40) NOT NULL,
mobile_01 CHAR(3) NOT NULL,
mobile_02 VARCHAR(4) NOT NULL,
mobile_03 CHAR(4) NOT NULL,
fax_01 VARCHAR(3),
fax_02 VARCHAR(4),
fax_03 VARCHAR(4),
biz_post LONGTEXT NOT NULL,
`read_cnt` BIGINT,
PRIMARY KEY(idx)
)ENGINE=INNODB;

CREATE TABLE qna(
idx INT NOT NULL AUTO_INCREMENT,
u_name VARCHAR(12) NOT NULL,
u_email VARCHAR(100) NOT NULL,
biz_name VARCHAR(120) NOT NULL,
country_name VARCHAR(40) NOT NULL,
mobile_01 CHAR(3) NOT NULL,
mobile_02 VARCHAR(4) NOT NULL,
mobile_03 CHAR(4) NOT NULL,
tel_01 VARCHAR(3),
tel_02 VARCHAR(4),
tel_03 VARCHAR(4),
qna_post LONGTEXT NOT NULL,
`read_cnt` BIGINT,
PRIMARY KEY(idx)
)ENGINE=INNODB;

CREATE TABLE `event`(
idx INT NOT NULL AUTO_INCREMENT,
event_tit VARCHAR(64) NOT NULL,
event_lv CHAR(1) NOT NULL,
event_time DATE NOT NULL,
event_content TEXT NOT NULL,
event_comment LONGTEXT NOT NULL,
event_img VARCHAR(64) NOT NULL,
PRIMARY KEY(idx)
)ENGINE=INNODB;
